### ISSUE TITLE
Help with Maps components and autocomplete

### ISSUE THREAD

**Issue by nicolaspiquerez** [bonnici/light-bootstrap-dashboard-angularcli#1]
Great work on this repository.
I tried to add an input text field with autocomplete in your maps component.

I have followed this tutorial [http://brianflove.com/2016/10/18/angular-2-google-maps-places-autocomplete/], it works but the integration is not great, I wonder how you would do it.

If you could add the input field in the maps component repo that could be great !

Thanks

**Comment by bonnici** [comment]
Hi, I want to keep the core repo as close to the light bootstrap dashboard sample as possible, but I made a [branch](https://github.com/bonnici/light-bootstrap-dashboard-angularcli/tree/maps-autocomplete) showing how I would do it if I was following that tutorial. It is a bit hacky but I haven't looked into the autocomplete API enough to say how I would do it differently.
